######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 21 21:24:59 2014
######################################################################

QT += network
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp Sensor.cpp lcd.cpp i2c.cpp
HEADERS += Sensor.h
